# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  workflow_dispatch:

env:
  _R_CHECK_FORCE_SUGGESTS_: "FALSE"

name: R-CMD-check.yaml

permissions: read-all

jobs:
  ci-1:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
         # - {os: macos-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}
         # - {os: ubuntu-latest,   r: 'devel', http-user-agent: 'release'}
         #- {os: ubuntu-latest,   r: 'release'}
         # - {os: ubuntu-latest,   r: 'oldrel-1'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          build_args: 'c("--no-manual","--compact-vignettes=gs+qpdf")'

# Run CI for R based on copy of https://eddelbuettel.github.io/r-ci/
  ci-2:
      runs-on: ${{ matrix.os }}
      name: ${{ matrix.os }} (${{ matrix.r }})

      strategy:
        fail-fast: false
        matrix:
          include:
            - {os: macOS-latest, r: '4.5.1' }
            - {os: ubuntu-latest, r: 'release'}
      steps:
        - uses: actions/checkout@v4

        - name: System
          if: ${{ matrix.os == 'macOS-latest' }}
          run: |
           sysctl -a;
           echo "RVER=${{matrix.r}}" >> $GITHUB_ENV;
           echo "_R_CHECK_SYSTEM_CLOCK_:0" >> $GITHUB_ENV

        - name: Bootstrap
          run: ./.github/r-ci.sh bootstrap

        - name: Dependencies
          run: ./.github/r-ci.sh install_all

        - name: Test
          run: ./.github/r-ci.sh run_tests

        # - name: Show install log
        #   run: cat $HOME/work/R6.tiledb/R6.tiledb/R6.tiledb.Rcheck/00install.out
        #   if: failure()
        #
        # - name: Show test log
        #   run: cat $HOME/work/R6.tiledb/R6.tiledb/R6.tiledb.Rcheck/00check.log
        #   if: failure()

        #- name: Coverage
        #  if: ${{ matrix.os == 'ubuntu-latest' }}
        #  run: ./.github/r-ci.sh coverage
